---
sidebar: sidebar 
permalink: concept_overview.html 
keywords: overview, concepts, features, use case, days, 14 days 
summary: Cloud Manager 可讓 IT 專家和雲端架構設計師使用 NetApp 的雲端解決方案、集中管理混合式多雲端基礎架構。 
---
= 深入瞭解 Cloud Manager
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


Cloud Manager 可讓 IT 專家和雲端架構設計師使用 NetApp 的雲端解決方案、集中管理混合式多雲端基礎架構。



== 功能

Cloud Manager 是企業級 SaaS 型管理平台、無論資料位於何處、都能讓您隨時掌控資料。

* 設定與使用 https://cloud.netapp.com/ontap-cloud["Cloud Volumes ONTAP"^] 實現跨雲端的高效率多重傳輸協定資料管理。
* 設定及使用檔案儲存服務： https://cloud.netapp.com/azure-netapp-files["Azure NetApp Files"^]、 https://cloud.netapp.com/cloud-volumes-service-for-aws["AWS 適用的 Cloud Volumes Service"^]和 https://cloud.netapp.com/cloud-volumes-service-for-gcp["適用於 Google Cloud Cloud Volumes Service"^]。
* 建立 ONTAP 磁碟區、備份至雲端、在混合雲中複寫資料、以及將冷資料分層至雲端、藉此探索及管理內部的支援功能。
* 實現像這樣的整合式雲端服務與軟體 https://cloud.netapp.com/cloud-compliance["雲端法規遵循"^]、 https://cloud.netapp.com/cloud-insights["Cloud Insights"^]、 https://cloud.netapp.com/cloud-backup-service["Cloud Backup Service"^]、 https://netapp.io/persistent-storage-provisioner-for-kubernetes/["Trident"^]等等。


https://cloud.netapp.com/cloud-manager["深入瞭解 Cloud Manager"^]。



== 支援的物件儲存供應商

Cloud Manager 可讓您管理雲端儲存設備、並在 Amazon Web Services 、 Microsoft Azure 及 Google Cloud 中使用雲端服務。



== 成本

Cloud Manager 軟體是由 NetApp 免費提供。

在大多數的工作中、 Cloud Manager 會提示您在雲端網路中部署 Connector 、這會導致雲端供應商對運算執行個體和相關儲存設備的收費。您可以選擇在內部環境中執行 Connector 軟體。



== Cloud Manager 的運作方式

Cloud Manager 包含與 NetApp Cloud Central 整合的 SaaS 型介面、以及可管理 Cloud Volumes ONTAP 各種效益和其他雲端服務的 Connectors 。



=== 軟體即服務

Cloud Manager 可透過存取 https://cloudmanager.netapp.com["SaaS 型使用者介面"^] 和 API 。這項 SaaS 體驗可讓您在最新功能發佈時自動存取、並在 Cloud Central 帳戶和 Connector 之間輕鬆切換。



=== NetApp Cloud Central

https://cloud.netapp.com["NetApp Cloud Central"^] 提供集中位置以供存取和管理 https://www.netapp.com/us/products/cloud-services/use-cases-for-netapp-cloud-services.aspx["NetApp 雲端服務"^]。透過集中式使用者驗證、您可以使用相同的認證資料集來存取 Cloud Manager 和 Cloud Insights 其他雲端服務、例如：

首次登入 Cloud Manager 時、系統會提示您建立 _Cloud Central 帳戶 _ 。此帳戶提供多租戶共享、可讓您在隔離的 _stap空間 _ 中組織使用者和資源。



=== 連接器

在大多數情況下、帳戶管理員需要在雲端或內部部署網路中部署 _Connector_ 。Connector 可讓 Cloud Manager 管理公有雲環境中的資源與程序。

連接器應隨時保持執行狀態。這對於您持續啟用的服務健全狀況和營運而言十分重要。

例如、連接器是 Cloud Volumes ONTAP 指功能健全及運作的關鍵元件。如果連接器電源關閉、 Cloud Volumes ONTAP 則在與連接器失去通訊超過 14 天之後、將會關閉此功能。

link:concept_connectors.html["深入瞭解何時需要連接器及其運作方式"]。
