---
sidebar: sidebar 
permalink: concept_connectors.html 
keywords: 'concept, connectors, learn about connectors, service connectors, what are connectors, what is a connector, what"s a connector, days, 14 days' 
summary: 在大多數情況下、您需要在雲端或內部部署網路中部署 Connector 。Connector 可讓 Cloud Manager 管理公有雲環境中的資源與程序。 
---
= 深入瞭解連接器
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在大多數情況下、帳戶管理員需要在雲端或內部部署網路中部署 _Connector_ 。Connector 可讓 Cloud Manager 管理公有雲環境中的資源與程序。



== 需要連接器時

需要連接器才能在 Cloud Manager 中使用下列任何功能：

* Cloud Volumes ONTAP
* 內部部署 ONTAP 的叢集
* 雲端法規遵循
* Kubernetes
* 備份至雲端
* 監控
* 內部分層
* 全域檔案快取
* Amazon S3 儲存區探索


連接器 * 不是 * * * 、是 Azure NetApp Files 視覺、 Cloud Volumes Service 視覺或 Cloud Sync 視覺的必要條件。


NOTE: 雖然不需要連接器來設定和管理 Azure NetApp Files 功能、但如果您想要使用 Cloud Compliance 來掃描 Azure NetApp Files 不實資料、則需要連接器。



== 支援的位置

下列位置支援連接器：

* Amazon Web Services
* Microsoft Azure
* Google Cloud
* 在您的內部環境中



NOTE: 如果您想在 Cloud Volumes ONTAP Google Cloud 中建立一個不完整的系統、那麼您也必須在 Google Cloud 上執行 Connector 。您無法使用在其他位置執行的 Connector 。



== 連接器應保持運作

連接器應隨時保持執行狀態。這對於您持續啟用的服務健全狀況和營運而言十分重要。

例如、連接器是 Cloud Volumes ONTAP 指功能健全及運作的關鍵元件。如果連接器電源關閉、 Cloud Volumes ONTAP 則在與連接器失去通訊超過 14 天之後、將會關閉此功能。



== 如何建立連接器

「帳戶管理員 Cloud Volumes ONTAP 」必須先建立連接器、工作區管理員才能建立運作環境、並使用上述任何其他功能。

帳戶管理員可以透過多種方式建立 Connector ：

* 直接從 Cloud Manager （建議）
+
** link:task_creating_connectors_aws.html["在 AWS 中建立"]
** link:task_creating_connectors_azure.html["在 Azure 中建立"]
** link:task_creating_connectors_gcp.html["在 GCP 中建立"]


* link:task_launching_aws_mktp.html["從 AWS Marketplace 取得"]
* link:task_launching_azure_mktp.html["來自 Azure Marketplace"]
* link:task_installing_linux.html["在現有的 Linux 主機上下載並安裝軟體"]


當您建立第一個 Cloud Volumes ONTAP 運作環境時、如果您還沒有 Cloud Manager 、 Cloud Manager 會提示您建立 Connector 。



== 權限

建立 Connector 需要特定權限、而且 Connector 執行個體本身需要另一組權限。



=== 建立 Connector 的權限

從 Cloud Manager 建立 Connector 的使用者需要特定權限、才能在您選擇的雲端供應商中部署執行個體。Cloud Manager 會在您建立 Connector 時提醒您權限要求。

https://mysupport.netapp.com/site/info/cloud-manager-policies["檢視每個雲端供應商的原則"^]。



=== Connector 執行個體的權限

Connector 需要特定的雲端供應商權限、才能代表您執行作業。例如、部署及管理 Cloud Volumes ONTAP 功能。

當您直接從 Cloud Manager 建立 Connector 時、 Cloud Manager 會以所需的權限來建立 Connector 。您無需做任何事。

如果您是從 AWS Marketplace 、 Azure Marketplace 或手動安裝軟體來建立 Connector 、則必須確保擁有適當的權限。

https://mysupport.netapp.com/site/info/cloud-manager-policies["檢視每個雲端供應商的原則"^]。



== 何時使用多個連接器

在某些情況下、您可能只需要一個連接器、但可能需要兩個以上的連接器。

以下是幾個範例：

* 您使用的是多雲端環境（ AWS 和 Azure ）、因此 AWS 中有一個連接器、 Azure 中有另一個連接器。每個系統都能管理 Cloud Volumes ONTAP 在這些環境中執行的不實系統。
* 服務供應商可能會使用一個 Cloud Central 帳戶來為客戶提供服務、而使用另一個帳戶來為其中一個業務單位提供災難恢復。每個帳戶都會有個別的 Connectors 。




== 何時在連接器之間切換

當您建立第一個 Connector 時、 Cloud Manager 會針對您所建立的每個額外工作環境、自動使用該 Connector 。建立額外的 Connector 之後、您必須在兩者之間切換、以查看每個 Connector 專屬的工作環境。

link:task_managing_connectors.html#switch-between-connectors["瞭解如何在連接器之間切換"]。



== 本機使用者介面

而您應該從執行幾乎所有的工作 https://cloudmanager.netapp.com["SaaS 使用者介面"^]、連接器上仍有本機使用者介面可供使用。需要從 Connector 本身執行的幾項工作需要使用此介面：

* link:task_configuring_proxy.html["設定 Proxy 伺服器"]
* 安裝修補程式（您通常會與 NetApp 人員一起安裝修補程式）
* 下載 AutoSupport 資訊（如有問題、通常由 NetApp 人員引導）


link:task_managing_connectors.html#accessing-the-local-ui["瞭解如何存取本機 UI"]。



== 連接器升級

只要有、 Connector 就會自動將其軟體更新至最新版本 link:reference_networking_cloud_manager.html["傳出網際網路存取"] 以取得軟體更新。
