---
sidebar: sidebar 
permalink: faq_saas.html 
keywords: faq, frequently asked questions, questions 
summary: 此常見問題集可解答與新 Cloud Manager SaaS 版本相關的重要問題。 
---
= Cloud Manager SaaS 的常見問題集
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
此常見問題集可解答與新 Cloud Manager SaaS 版本相關的重要問題。



== Cloud Manager SaaS 版本於 2020 年 8 月 3 日推出哪些功能？

* * 統一化的 API 與 UI*
+
統一化且集中化的 API 控制面板、適用於所有 NetApp ONTAP 型儲存解決方案、為客戶提供下列管理與控制：

+
** Azure NetApp Files
** AWS 適用的 Cloud Volumes Service
** 適用於 Google Cloud Cloud Volumes Service
** Cloud Volumes ONTAP


* * 無縫整合 NetApp 資料服務 *
+
為了順暢整合、儲存解決方案內建可輕鬆整合的資料服務。

* * 集中管理多種環境 *
+
現在、多種環境的部署與管理作業已經簡化。在先前的版本中、客戶必須在每個理想位置部署 Cloud Manager 執行個體。在新版本中、 Cloud Manager 代理程式現已重新命名為 _Connector_ 。

+
擁有多個 NetApp Cloud Central 帳戶或連接器的使用者可以輕鬆地在不同的帳戶和環境之間切換。

* * 用於 API 和 UI* 的公共端點
+
有了新版本、您可以透過安全存取 Cloud Manager 的 API 和 GUI  https://cloudmanager.netapp.com[]。





== 部署在 VPC/vnet 中的 Cloud Manager 執行個體會發生什麼事？

如上所述、部署在客戶網路中的 Cloud Manager 執行個體現在稱為 _Connector_ 。

Connector 的角色並未改變。它的目的與過去相同、就是管理客戶公有雲網路中的資源與程序。



== 現在我可以移除使用 SaaS 平台的 Connector 嗎？

不、您不應該。Connector 是用來管理公有雲環境中資源和程序的軟體、例如部署和管理 Cloud Volumes ONTAP 、 Cloud Backup Service 啟用功能、部署 Cloud Compliance 等等。



== 我是否仍能像以前一樣使用 Cloud Manager （透過部署在 VPC 上的執行個體、在本機上使用）？

是的、您可以按一下 * Connector* 功能表、然後按一下 * 移至本機 UIP* 、或直接在網頁瀏覽器中輸入 Connector 的 IP 位址來執行此作業。



== 移轉至 Cloud Manager SaaS 是否需要移轉或採取任何特定行動？

無需任何操作。只要瀏覽即可 https://cloudmanager.netapp.com[] 並開始工作。顯然、只有授權使用者才能存取 Cloud Manager 。



== 其中的資料是不一樣的、還是 Cloud Volumes ONTAP 儲存在任何地方的資料會有所改變或移動？

不可以無論是 VPC 或 Vnet 、都能在您的管理之下、隨時保持不變。



== Cloud Manager SaaS 平台的端點在哪裡？

它由 NetApp 在公有雲上安全營運。



== 在 Cloud Manager SaaS 服務層中儲存了哪些類型的資料或中繼資料？

Cloud Manager SaaS 服務層不會儲存任何資料。

SaaS 平台是在使用者的網頁瀏覽器和本機連接器之間、或是整合至 Cloud Manager 的不同 NetApp 服務之間、作為 API 呼叫（ HTTPS 搭配 NetApp 簽署憑證）的安全管道。



== 部署在 VPC/vnet 中的 Connector 會儲存哪些資料或中繼資料？

Connector / Cloud Manager 尚未變更。它儲存的資料與先前版本相同。它只保留必要的中繼資料、以管理公有雲環境中的資源和程序、例如部署和管理 Cloud Volumes ONTAP 、 Cloud Backup Service 啟用效益、部署和使用雲端法規遵循等（請參閱 link:concept_connectors.html["深入瞭解連接器"] 頁面以取得完整的服務清單）。



== 什麼是資料和中繼資料路徑？

連接器與客戶之間的資料會透過 HTTPS 傳輸、並以 NetApp 憑證進行加密和簽名。SaaS 型 UI 是用戶端網頁瀏覽器與 Connector 之間的安全管道。這表示只有授權使用者才能存取 Connector 的資料。

對於使用雲端法規遵循服務的客戶、它現在是端點對端點加密的金鑰交換會在網路瀏覽器與 Connector 之間進行、因此 NetApp 無法讀取任何資料。 https://cloud.netapp.com/cloud-compliance["深入瞭解雲端法規遵循"^]。



== 透過 SaaS 端點使用雲端法規遵循服務時、 GDPR 是否會有影響？

資料會加密端點對端點金鑰交換會在網路瀏覽器與 Connector 之間進行、因此 NetApp 無法讀取任何資料。



== SaaS 型 UI 和 API 使用哪種網路方向存取來存取 Connector ？

* 客戶的 VPC/vnet 與 SaaS 型 UI 之間的通訊只是 _ 傳出 _ 、這表示它只由 Connector 啟動。
* Connector 會在安全通道上輪詢 SaaS 型服務層的更新。
* 所有 API 呼叫都會使用驗證和授權來確保存取安全無虞。
+
這表示您不需要開啟網路中的其他連接埠 / 端點。

* 使用者瀏覽器用戶端與 SaaS 型 UI 之間的通訊使用 HTTPS 搭配 NetApp 簽署的憑證。




== 登入流程是否有所變更？

否、登入流程與先前版本相同。當使用者登入（ SSO 或認證）時、就會根據驗證 0 進行驗證、就像以前一樣。

請注意下列事項：

* 如果 SSO 或聯盟已就緒、則仍會採用與目前相同的安全程序。存取權是貴公司機構的聯盟。使用聯盟存取時、您可以自行新增 MFA （由貴公司自行決定）、以提高安全性。
* 角色或權限沒有變更。只有向 Cloud Central 帳戶註冊的使用者才能存取 SaaS 型端點。
* 目前不支援使用無痕式模式、或是用戶端瀏覽器不允許使用協力廠商 Cookie 的組態。




== SaaS 型 Cloud Manager 是否符合法規（ SOC2 、 FedRAMP 等）？

Cloud Manager 正在取得 SOC2 認證。

為了符合FedRAMP認證、不針對需要FedRAMP的客戶啟用SaaS型UI。
