---
sidebar: sidebar 
permalink: faq_cloud_tiering.html 
keywords: faq, questions, requirements, service connector, object store, object storage, aws, azure, bucket, cluster, aggregate, s3, storage class, standard, inactive data reporting, auto, volume tiering policy, policy, tiering policy, snapshot, cold, inactive, infrequent 
summary: 如果您只是想要快速回答問題、這個常見問題集就能幫上忙。 
---
= 雲端分層技術常見問題集
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
如果您只是想要快速回答問題、這個常見問題集就能幫上忙。



== ONTAP

下列問題 ONTAP 與不相關。



=== 我的整個叢集有哪些需求 ONTAP ？

這取決於您分層 Cold 資料的位置。請參閱下列內容：

* link:task_tiering_onprem_aws.html#preparing-your-ontap-clusters["將內部部署 ONTAP 的資料叢集分層至 Amazon S3"]
* link:task_tiering_onprem_azure.html#preparing-your-ontap-clusters["將內部部署 ONTAP 的資料叢集分層至 Azure Blob 儲存設備"]
* link:task_tiering_onprem_gcp.html#preparing-your-ontap-clusters["將內部部署 ONTAP 的資料叢集分層至 Google Cloud Storage"]
* link:task_tiering_onprem_storagegrid.html#preparing-your-ontap-clusters["將內部部署 ONTAP 的資料叢集分層至 StorageGRID 不再需要"]




=== 雲端分層是否能啟用非作用中的資料報告？

是的、雲端分層可在每個 Aggregate 上啟用非作用中資料報告。此設定可讓我們識別可分層至低成本物件儲存的非使用中資料量。



=== 我可以從 NAS 磁碟區和 SAN 磁碟區來分層資料嗎？

您可以使用 Cloud Tiering 將資料從 NAS 磁碟區分層至公有雲、並使用 StorageGRID 效益技術將 SAN 磁碟區的資料分層至私有雲。



=== 關於此功能呢 Cloud Volumes ONTAP ？

如果您使用Cloud Volumes ONTAP 的是支援功能、您可以在叢集儀表板中找到這些功能、以便在混合雲基礎架構中查看資料分層的完整檢視。

從叢集儀表板、您可以檢視與內部 ONTAP 叢集類似的分層資訊：作業健全狀況、目前的節約效益、節約機會、磁碟區與集合體的詳細資料等。

從 Cloud Tiering 讀取系統。 Cloud Volumes ONTAP您無法從 Cloud Volumes ONTAP Cloud Tiering 設定資料分層功能。您仍會以同樣的方式設定分層：從 Cloud Manager 的工作環境開始。



== 物件儲存

下列問題與物件儲存有關。



=== 支援哪些物件儲存供應商？

支援 Amazon S3 、 Azure Blob 儲存設備、 Google Cloud Storage 及 StorageGRID 使用 S3 傳輸協定的功能。



=== 我可以使用自己的桶 / 容器嗎？

是的、您可以。當您設定資料分層時、可以選擇新增庫位 / 容器、或是選取現有的庫位 / 容器。



=== 支援哪些地區？

* link:reference_aws_support.html["支援的 AWS 區域"]
* link:reference_azure_support.html["支援的 Azure 地區"]
* link:reference_google_support.html["支援的 Google Cloud 地區"]




=== 支援哪些 S3 儲存類別？

雲端分層可支援資料分層至 _Standard_ 、 _Standard-in頻繁 存取 _ 、 _one Zone -IA_ 或 _Intelligent _ 儲存類別。請參閱 link:reference_aws_support.html["支援的 S3 儲存類別"] 以取得更多詳細資料。



=== 支援哪些 Azure Blob 存取層？

雲端分層會自動使用 _hot_ 存取層來處理您的非使用中資料。



=== Google Cloud Storage 支援哪些儲存類別？

雲端分層使用 _Standard_ 儲存類別來處理非作用中資料。



=== 雲端分層會將一個物件存放區用於整個叢集、還是每個 Aggregate 使用一個物件存放區？

一個物件存放區用於整個叢集。



=== 我可以將原則套用到物件存放區、以便在分層不受限制的情況下移動資料嗎？

否、雲端分層不支援從物件存放區移動或刪除資料的物件生命週期管理規則。



== 連接器

下列問題與連接器有關。



=== 連接器需要安裝在何處？

* 將資料分層至 S3 時、連接器可位於 AWS VPC 或內部部署環境中。
* 將資料分層至 Blob 儲存設備時、連接器必須位於 Azure vnet 中。
* 將資料分層至 Google Cloud Storage 時、 Connector 必須位於 Google Cloud Platform VPC 中。
* 將資料分層至 StorageGRID 物件時、連接器必須位於內部部署的 Linux 主機上。




== 網路

下列問題與網路有關。



=== 網路需求為何？

* 此支援叢集可透過連接埠 443 、啟動 HTTPS 連線至您的物件儲存設備供應商。 ONTAP
+
可在物件儲存設備中讀取及寫入資料。 ONTAP物件儲存設備從未啟動、只是回應而已。

* 對於 StorageGRID 僅供使用的物件、 ONTAP 支援使用者指定的連接埠來啟動 HTTPS 連線 StorageGRID 至物件（連接埠可在分層設定期間設定）。
* 連接器需要透過連接埠 443 連至 ONTAP 您的叢集、物件存放區和雲端分層服務的輸出 HTTPS 連線。


如需詳細資料、請參閱：

* link:task_tiering_onprem_aws.html["將內部部署 ONTAP 的資料叢集分層至 Amazon S3"]
* link:task_tiering_onprem_azure.html["將內部部署 ONTAP 的資料叢集分層至 Azure Blob 儲存設備"]
* link:task_tiering_onprem_gcp.html["將內部部署 ONTAP 的資料叢集分層至 Google Cloud Storage"]
* link:task_tiering_onprem_storagegrid.html["將內部部署 ONTAP 的資料叢集分層至 StorageGRID 不再需要"]




== 權限

下列問題與權限有關。



=== AWS 需要哪些權限？

需要權限 link:task_tiering_onprem_aws#preparing-amazon-s3["管理 S3 儲存區"]。



=== Azure 需要哪些權限？

您不需要在 Cloud Manager 所需的權限範圍之外、額外權限。



=== Google Cloud Platform 需要哪些權限？

具有儲存存取金鑰的服務帳戶需要儲存管理權限。



=== 需要哪些權限 StorageGRID 才能執行此功能？

link:task_tiering_onprem_storagegrid.html#preparing-storagegrid["需要 S3 權限"]。
