---
sidebar: sidebar 
permalink: reference_cloud_mgr_reqs.html 
keywords: configurations, ec2, vm, ports, ram, operating system, os, host, requirement, requirements, hypervisor, disk, space, mysql, centos, rhel, red hat, cpu, disk space, 3306 
summary: Connector 軟體必須在符合特定作業系統需求、 RAM 需求、連接埠需求等的主機上執行。 
---
= 連接器主機需求
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Connector 軟體必須在符合特定作業系統需求、 RAM 需求、連接埠需求等的主機上執行。

需要專用主機:: 與其他應用程式共用的主機不支援 Connector 。主機必須是專屬主機。
CPU:: 4 個核心或 4 個 vCPU
RAM:: 14 GB
AWS EC2 執行個體類型:: 符合上述 CPU 和 RAM 需求的執行個體類型。建議您直接從 Cloud Manager 部署 Connector 時、使用 T3.xLarge 執行個體類型。
Azure VM 大小:: 符合上述 CPU 和 RAM 需求的執行個體類型。我們建議使用 DS3 v2 、並在直接從 Cloud Manager 部署 Connector 時使用該 VM 大小。
GCP 機器類型:: 符合上述 CPU 和 RAM 需求的執行個體類型。我們建議您使用 n1-Standard-4 、並在直接從 Cloud Manager 部署 Connector 時使用該機器類型。
支援的作業系統::
+
--
* CentOS 7.6.
* CentOS 7.7
* Red Hat Enterprise Linux 7.6
* Red Hat Enterprise Linux 7.7
+
Red Hat Enterprise Linux 系統必須在 Red Hat 訂購管理中註冊。如果未登錄、系統將無法在 Connector 安裝期間存取儲存庫來更新所需的協力廠商軟體。

+
這些作業系統的英文版本支援 Connector 。



--
Hypervisor:: 通過認證可執行 CentOS 或 Red Hat Enterprise Linux 的裸機或託管 Hypervisorhttps://access.redhat.com/certified-hypervisors["Red Hat 解決方案：哪些 Hypervisor 已通過認證、可執行 Red Hat Enterprise Linux ？"^]
/opt 中的磁碟空間:: 必須有 100 GB 的可用空間
傳出網際網路存取:: 安裝 Connector 和 Connector 時、需要外傳網際網路存取、才能管理公有雲環境中的資源和程序。如需端點清單、請參閱 link:reference_networking_cloud_manager.html["連接器的網路需求"]。

