---
sidebar: sidebar 
permalink: reference_default_configs.html 
keywords: svm, LIF, LIFs, configuration backups, attributes, autosize, security style, space guarantee, unix permissions, NTFS, UNIX, boot, root, disks, aggr0, aggr1, svm, svms, storage virtual machine, LIF failover, failover, attributes, volume attributes, boot disk, root disk, licenses, feature licenses, default licenses, ontap licenses, ontap features 
summary: 瞭解 Cloud Volumes ONTAP 根據預設設定的功能可協助您設定及管理系統、尤其是熟悉 ONTAP 使用功能時、因為 Cloud Volumes ONTAP 預設的功能與 ONTAP 使用功能不相同、所以使用功能不一。 
---
= 的預設組態 Cloud Volumes ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
瞭解 Cloud Volumes ONTAP 根據預設設定的功能可協助您設定及管理系統、尤其是熟悉 ONTAP 使用功能時、因為 Cloud Volumes ONTAP 預設的功能與 ONTAP 使用功能不相同、所以使用功能不一。



== 預設值

* 可在AWS、Azure和GCP中作為單一節點系統使用、也可在AWS和Azure中作為HA配對使用。Cloud Volumes ONTAP
* Cloud Manager 部署 Cloud Volumes ONTAP 時會建立一個資料服務儲存 VM 、部分組態支援額外的儲存 VM 。 link:task_managing_svms.html["深入瞭解管理儲存 VM"]。
* Cloud Manager 會自動在 ONTAP 下列功能授權上安裝 Cloud Volumes ONTAP 於更新：
+
** CIFS
** FlexCache
** FlexClone
** iSCSI
** NetApp Volume Encryption （僅適用於 BYOL 或註冊的 PAYGO 系統）
** NFS
** SnapMirror
** SnapRestore
** SnapVault


* 預設會建立多個網路介面：
+
** 叢集管理 LIF
** 叢集間 LIF
** Azure中HA系統上的SVM管理LIF、AWS中的單一節點系統、以及多個AWS可用性區域中的HA系統（可選）
** 節點管理 LIF
** iSCSI 資料 LIF
** CIFS 與 NFS 資料 LIF
+

NOTE: 由於 Cloud Volumes ONTAP EC2 需求、 LIF 容錯移轉功能預設為停用。將 LIF 移轉至其他連接埠會中斷執行個體上 IP 位址與網路介面的外部對應、使 LIF 無法存取。



* 使用 HTTPS 將組態備份傳送至 Connector 。 Cloud Volumes ONTAP
+
可從存取備份 https://ipaddress/occm/offboxconfig/[] 其中 _ipaddress_ 是連接器主機的 IP 位址。

* Cloud Manager 設定的磁碟區屬性與其他管理工具（例如 System Manager 或 CLI ）有所不同。
+
下表列出 Cloud Manager 設定的 Volume 屬性與預設值不同：

+
[cols="15,85"]
|===
| 屬性 | Cloud Manager 設定的價值 


| 自動調整大小模式 | 成長 


| 最大自動調整大小  a| 
1 、 000 %


NOTE: 帳戶管理員可從「設定」頁面修改此值。



| 安全風格 | 適用於 CIFS Volume UNIX for NFS Volume 的 NTFS 


| 空間保證風格 | 無 


| UNIX 權限（僅限 NFS ） | 777 
|===
+
有關這些屬性的信息，請參見 _volume creation_ 手冊頁。





== 開機和root資料Cloud Volumes ONTAP 以供使用

除了儲存使用者資料之外、Cloud Manager也會購買雲端儲存設備、以便在每Cloud Volumes ONTAP 個作業系統上開機和取得根資料。



=== AWS

* 每個節點兩個磁碟用於開機和根資料：
+
** 9.7 ： 160 GB IO1 磁碟用於開機資料、 220 GB gp2 磁碟用於根資料
** 9.6 ： 93 GB IO1 磁碟用於開機資料、 140 GB gp2 磁碟用於根資料
** 9.5 ： 45 GB IO1 磁碟用於開機資料、 140 GB gp2 磁碟用於根資料


* 每個開機磁碟和根磁碟各一份 EBS 快照
* 對於 HA 配對、一個 EBS 磁碟區用於「內化器」執行個體、約 8 GB




=== Azure （單一節點）

* 三個優質 SSD 磁碟：
+
** 一個 10 GB 磁碟用於開機資料
** 一個 140 GB 磁碟用於根資料
** 一個 128 GB 磁碟用於 NVRAM
+
如果您選擇 Cloud Volumes ONTAP 的虛擬機器支援 Ultra SSD 、則系統會使用 Ultra SSD 來執行 NVRAM 、而非使用 Premium SSD 。



* 一個 10GB 標準 HDD 磁碟、可節省核心
* 每個開機磁碟和根磁碟各一份 Azure 快照




=== Azure （ HA 配對）

* 兩個 10 GB Premium SSD 磁碟用於開機磁碟區（每個節點一個）
* 兩個 140 GB Premium Storage 頁面、用於根磁碟區（每個節點一個）
* 兩個 10GB 標準 HDD 磁碟、可節省核心（每個節點一個）
* 兩個 128 GB Premium SSD 磁碟用於 NVRAM （每個節點一個）
* 每個開機磁碟和根磁碟各一份 Azure 快照




=== GCP

* 一個 10 GB 標準持續磁碟用於開機資料
* 一個 64 GB 標準持續磁碟用於根資料
* 一個 500 GB 標準持續磁碟用於 NVRAM
* 一個216 GB標準持續磁碟、用於儲存核心
* 每個 GCP 快照一個用於開機磁碟和根磁碟




=== 磁碟所在位置

Cloud Manager 的儲存設備如下所示：

* 開機資料位於附加至執行個體或虛擬機器的磁碟上。
+
此磁碟包含開機映像、 Cloud Volumes ONTAP 不適用於 Image.

* 根資料包含系統組態和記錄檔、位於 aggr0 中。
* 儲存虛擬機器（ SVM ）根磁碟區位於 aggr1 中。
* 資料磁碟區也位於 aggr1 中。




=== 加密

Azure 和 Google Cloud Platform 會一律加密開機和根磁碟、因為這些雲端供應商預設會啟用加密功能。

當您使用金鑰管理服務（ KMS ）在 AWS 中啟用資料加密時、 Cloud Volumes ONTAP 也會加密適用於此功能的開機磁碟和根磁碟。這包括 HA 配對中中介執行個體的開機磁碟。磁碟會使用您在建立工作環境時所選取的 CMK 進行加密。
