---
sidebar: sidebar 
permalink: task_planning_your_config_gcp.html 
keywords: license, disk, ebs, storage, size, write speed, volume usage, explore, standard, premium, byol, capacity, limit, configurations, virtual machine, vm, regions, supported disks, disk types, use profile, thin provisioning, deduplication, compression, Cloud Volumes ONTAP explore, Cloud Volumes ONTAP standard, Cloud Volumes ONTAP premium, Cloud Volumes ONTAP byol, shared instance, dedicated instance, write speed, high write speed, normal write speed, network information, worksheet, limit, limits, storage limits, volume limit, aggregate limit, maximum volume size, maximum aggregate size 
summary: 部署 Cloud Volumes ONTAP 時、您可以選擇符合工作負載需求的預先設定系統、或是建立自己的組態。如果您選擇自己的組態、應該瞭解可用的選項。 
---
= 在 Cloud Volumes ONTAP Google Cloud 規劃您的不一樣組態
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在 Cloud Volumes ONTAP Google Cloud 中部署時、您可以選擇符合工作負載需求的預先設定系統、或是建立自己的組態。如果您選擇自己的組態、應該瞭解可用的選項。



== 選擇授權類型

提供兩種定價選項：隨用隨付及自帶授權（ BYOL ） Cloud Volumes ONTAP 。若為隨用隨付、您可以從三種授權中選擇： Explore 、 Standard 或 Premium 。每個授權都提供不同的容量和運算選項。

https://docs.netapp.com/us-en/cloud-volumes-ontap/reference_configs_gcp_97.html["支援的GCP中的VMWare 9.7組態Cloud Volumes ONTAP"^]



== 瞭解儲存限制

一個不含資源的系統的原始容量上限 Cloud Volumes ONTAP 與授權有關。其他限制會影響集合體和磁碟區的大小。在規劃組態時、您應該注意這些限制。

https://docs.netapp.com/us-en/cloud-volumes-ontap/reference_limits_gcp_97.html["GCP中的更新儲存限制Cloud Volumes ONTAP"]



== 在 GCP 中調整系統規模

調整 Cloud Volumes ONTAP 您的支援規模、有助於滿足效能與容量的需求。在選擇機器類型、磁碟類型和磁碟大小時、您應該注意幾個關鍵點：

機器類型:: 請查看中支援的機器類型 http://docs.netapp.com/cloud-volumes-ontap/us-en/index.html["發行說明 Cloud Volumes ONTAP"^] 然後檢視 Google 提供的每種受支援機器類型的詳細資料。將工作負載需求與機器類型的 vCPU 和記憶體數量配對。請注意、每個 CPU 核心都能提升網路效能。
+
--
如需詳細資料、請參閱下列內容：

* https://cloud.google.com/compute/docs/machine-types#n1_machine_types["Google Cloud 文件： N1 標準機器類型"^]
* https://cloud.google.com/docs/compare/data-centers/networking#performance["Google Cloud 文件：效能"^]


--
GCP 磁碟類型:: 當您建立 Cloud Volumes ONTAP 用於資料的 Volume 時、您需要選擇 Cloud Volumes ONTAP 基礎雲端儲存設備、以便將其用於磁碟。磁碟類型可以是 _ 分區 SSD 持續磁碟 _ 或 _ 分區標準持續磁碟 _ 。
+
--
SSD 持續式磁碟最適合需要高隨機 IOPS 的工作負載、而標準持續式磁碟則經濟實惠、可處理連續讀寫作業。如需詳細資料、請參閱 https://cloud.google.com/compute/docs/disks/#pdspecs["Google Cloud 文件：分區持續磁碟（標準和 SSD ）"^]。

--
GCP 磁碟大小:: 部署 Cloud Volumes ONTAP 一套系統時、您需要選擇初始磁碟大小。之後、您可以讓 Cloud Manager 為您管理系統容量、但如果您想自行建置集合體、請注意下列事項：
+
--
* 集合體中的所有磁碟大小必須相同。
* 判斷您需要的空間、同時考量效能。
* 持續性磁碟的效能會隨著磁碟大小和系統可用的 vCPU 數目而自動擴充。
+
如需詳細資料、請參閱下列內容：

+
** https://cloud.google.com/compute/docs/disks/#pdspecs["Google Cloud 文件：分區持續磁碟（標準和 SSD ）"^]
** https://cloud.google.com/compute/docs/disks/performance["Google Cloud 文件：最佳化持續磁碟和本機 SSD 效能"^]




--




== GCP 網路資訊工作表

在 Cloud Volumes ONTAP GCP 中部署時、您需要指定虛擬網路的詳細資料。您可以使用工作表向系統管理員收集資訊。

[cols="30,70"]
|===
| GCP 資訊 | 您的價值 


| 區域 |  


| 區域 |  


| VPC 網路 |  


| 子網路 |  


| 防火牆原則（如果使用您自己的） |  
|===


== 選擇寫入速度

Cloud Manager可讓您選擇單一節點Cloud Volumes ONTAP 的寫入速度設定。在您選擇寫入速度之前、您應該先瞭解一般與高設定之間的差異、以及使用高速寫入速度時的風險與建議。



==== 正常寫入速度與高速寫入速度之間的差異

當您選擇正常寫入速度時、資料會直接寫入磁碟、因此可降低發生非計畫性系統中斷時發生資料遺失的可能性。

選擇高速寫入速度時、資料會在寫入磁碟之前先緩衝到記憶體中、以提供更快的寫入效能。由於這種快取、如果發生非計畫性的系統中斷、可能會導致資料遺失。

發生非計畫性系統中斷時可能遺失的資料量、是最後兩個一致點的範圍。一致點是將緩衝資料寫入磁碟的行為。寫入日誌已滿或 10 秒後（以先到者為準）、就會出現一致點。然而、AWS EBS Volume效能可能會影響一致點處理時間。



==== 何時使用高速寫入

如果您的工作負載需要快速寫入效能、而且在非計畫性的系統中斷時、您可以承受資料遺失的風險、那麼高速寫入速度是很好的選擇。



==== 使用高速寫入速度時的建議事項

如果啟用高速寫入、則應確保應用程式層的寫入保護。



== 選擇 Volume 使用設定檔

包含多項儲存效率功能、可減少您所需的總儲存容量。 ONTAP在 Cloud Manager 中建立 Volume 時、您可以選擇啟用這些功能的設定檔、或是停用這些功能的設定檔。您應該深入瞭解這些功能、以協助您決定要使用的設定檔。

NetApp 儲存效率功能提供下列效益：

資源隨需配置:: 為主機或使用者提供比實體儲存資源池實際擁有更多的邏輯儲存設備。儲存空間不會預先配置儲存空間、而是會在寫入資料時動態分配給每個磁碟區。
重複資料刪除:: 找出相同的資料區塊、並以單一共用區塊的參考資料取代這些區塊、藉此提升效率。這項技術可消除位於同一個磁碟區的備援資料區塊、進而降低儲存容量需求。
壓縮:: 藉由壓縮主儲存設備、次儲存設備和歸檔儲存設備上磁碟區內的資料、來減少儲存資料所需的實體容量。

